### ISSUE TITLE
Fix debug option

### ISSUE THREAD

**Issue by SamTebbs33** [SamTebbs33/pluto#70]
The help text for the `zig build` debug option is confusing, since it says that it causes the kernel to be built with debug info but this happens irrespective of the option's value. As it stands, our options are

* The option should be removed (meaning `zig build run` will have to be branched out to `zig build run-debug`).
* It should be made true by default.
* It should be made false by default.

For option 2 and 3, a value of  false will mean we have to strip the debug info from the build with `--strip` or the equivalent `build.zig` function.

**Comment by DrDeano** [comment]
I think we should keep it simple, where `zig build` will build a release version, else provide  `-Ddebug` option (default to false) where the user can build a debug version. Same with `zig build run` and `zig build test` where by default will build a release and run or test. Pass a option so to build and run/test in a different mode. Actually, instead of the `-Ddebug` option, can have `-Dbuild_mode=<mode>` where mode will be one of the zig build modes. (debug, release-safe, release-fast, release-small). Then the default build for release can be release-safe. Then for the debug info, only the `-Dbuild_mode=debug` will provide this and the others will `--strip`. But I assume the release build will strip the debug stuff anyway. This will also make it easy to parallelise the building and testing on the CI as will just have 4 `zig build test -Dbuild_mode=...` all separate.

**Comment by SamTebbs33** [comment]
Agreed on using the normal release options. Then we can have `run` and `debug-run` steps for running the kernel.

**Comment by DrDeano** [comment]
The `run` and `debug-run` can just be `zig build run` and `zig build run -Dbuild_mode=debug` so it is consistence across the building, bc `run` will run what is built, so you want to have pluto be built with `-Dbuild_mode=debug` then `run` will run the debug built binary.

**Comment by SamTebbs33** [comment]
Using a build mode argument when running feels a bit weird since running shouldn't actually *build* the kernel.

**Comment by DrDeano** [comment]
But, to run, you have: `zig build run` where build is the first action and run is the second, it would make sense if it was just `zig run` then `zig debug-run` would be fine, but bc `zig build run` will build first then run.
